# Generated by Django 5.1.7 on 2025-04-03 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('list_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('list_title', models.CharField(max_length=20)),
                ('list_type', models.CharField(choices=[('1', 'checklist'), ('2', 'to do'), ('3', 'groceries'), ('4', 'custom')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=30)),
                ('subscription', models.CharField(choices=[('P', 'premium'), ('S', 'standard')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ListItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20)),
                ('notes', models.CharField(max_length=40)),
                ('is_done', models.BooleanField()),
                ('due', models.DateField()),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist_app.lists')),
            ],
        ),
        migrations.AddField(
            model_name='lists',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist_app.users'),
        ),
    ]
