# Generated by Django 5.1.7 on 2025-04-04 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listitems',
            old_name='list_id',
            new_name='list',
        ),
        migrations.RenameField(
            model_name='lists',
            old_name='user_id',
            new_name='user',
        ),
    ]
