# Generated by Django 5.1.7 on 2025-04-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist_app', '0002_rename_list_id_listitems_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists',
            name='list_type',
            field=models.CharField(choices=[('1', 'checklist'), ('2', 'to do'), ('3', 'groceries'), ('4', 'custom')], default='checklist', max_length=1),
        ),
        migrations.AlterField(
            model_name='users',
            name='subscription',
            field=models.CharField(choices=[('P', 'premium'), ('S', 'standard')], default='standard', max_length=1),
        ),
    ]
