# Generated by Django 5.1.7 on 2025-04-26 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist_app', '0003_alter_lists_list_type_alter_users_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='listitems',
            old_name='item_name',
            new_name='itemName',
        ),
        migrations.RenameField(
            model_name='lists',
            old_name='list_id',
            new_name='listId',
        ),
        migrations.RemoveField(
            model_name='listitems',
            name='due',
        ),
        migrations.RemoveField(
            model_name='listitems',
            name='is_done',
        ),
        migrations.RemoveField(
            model_name='listitems',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='lists',
            name='list_title',
        ),
        migrations.RemoveField(
            model_name='lists',
            name='list_type',
        ),
        migrations.AddField(
            model_name='lists',
            name='listTitle',
            field=models.CharField(default='New List', max_length=30),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
