# Generated by Django 5.1.7 on 2025-04-29 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist_app', '0004_alter_lists_user_rename_item_name_listitems_itemname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listitems',
            old_name='list',
            new_name='listId',
        ),
    ]
