# Generated by Django 5.1.7 on 2025-05-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist_app', '0005_rename_list_listitems_listid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lists',
            old_name='user',
            new_name='username',
        ),
        migrations.AddField(
            model_name='listitems',
            name='isDone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listitems',
            name='notes',
            field=models.CharField(default='', max_length=100),
        ),
    ]
