# Generated by Django 5.1.7 on 2025-05-02 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist_app', '0007_rename_username_lists_user_listitems_createdby_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitems',
            name='notes',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
