# Generated by Django 5.1.7 on 2025-05-07 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist_app', '0008_remove_lists_username_lists_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitems',
            name='itemName',
            field=models.CharField(max_length=40),
        ),
    ]
