# Generated by Django 5.1.7 on 2025-05-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist_app', '0009_remove_lists_username_lists_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists',
            name='listTitle',
            field=models.CharField(default='Checklist', max_length=30),
        ),
    ]
